### ISSUE TITLE
Bugfix: Checkbox marker remain invisible in active state

### ISSUE THREAD

**Issue by iamfio** [simeonkerkola/after-dark#14]
Hello and thank you for this great theme. I've been using it for a few years already and not so long time ago I jumped from Postman to Thunder Client in VS Code. Now I'm facing some small Issues with the Checkbox state in it. Even in the checked state, the checkbox remains unchecked, as shown in the screenshot. And thanks again for the theme!

![image](https://user-images.githubusercontent.com/115066736/207818428-2a04cb33-f39b-4925-af41-844540a93a49.png)

**Comment by simeonkerkola** [comment]
Thanks for the feedback 👍
This is now fixed in v1.6.3

**Comment by iamfio** [comment]
Thank you for your response and fix. Now it works fine 👌
